### ISSUE TITLE
Hey there, I really like this idea. But I have a question...

### ISSUE THREAD

**Issue by millermk1717** [Jitensid/TabPort#1]
Does it have to be a json file? I'm not a developer and am not familiar with working with json files. I just think it'd be pretty cool if the tab lists were html or even just plain text files so that there would be some more opportunities for sharing them and using them in different ways.

Basically I've used Session Buddy for a long time, but although you can search in SB, you don't have full freedom to look at creation dates and whatnot. So I like this idea of quickly downloading the session onto the filesystem where, in theory, you can manipulate, sort, and search through you saved sessions. 

Anyways, I'll be keeping an eye out for further development, thanks!

**Comment by Jitensid** [comment]
Hello @millermk1717 . I am really glad that you like this extension. The extension can definitely support other file types such as txt and csv files. One use case I can think with text files is that if user wants to merge 2 or more text files they can do it easily and load them quickly in a single upload. What other use cases do you have if tabs are stored in the text file format ?

**Comment by Jitensid** [comment]
Hello @millermk1717 . Thanks to the contributions from F1nn-T this issue is closed now. 
Good job @F1nn-T
