### ISSUE TITLE
Improving Jest Test Cases Code Coverage

### ISSUE THREAD

**Issue by Jitensid** [Jitensid/TabPort#17]
Recently many new features are implemented but this has also reduced the code coverage of the overall codebase. Hence interested contributors who have knowledge of **Jest** are requested to write test cases for the same to improve the overall code coverage of the repository.

**Comment by zluipaiva** [comment]
hello, I would like to work on this

**Comment by Jitensid** [comment]
Sure. Good luck

**Comment by CalArcher** [comment]
Can I also work on this?

**Comment by Jitensid** [comment]
Sure. Good luck

**Comment by Jitensid** [comment]
Try to keep code coverage >= **90%**

**Comment by Jitensid** [comment]
Thanks for the support !
