### ISSUE TITLE
Text file support for TabPort Extension

### ISSUE THREAD

**Issue by Jitensid** [Jitensid/TabPort#6]
Currently the [TabPort chrome extension ](https://chrome.google.com/webstore/detail/tabport/dhkmlpcfghaaiiomhfdndoeghjmimafn)has the ability to download and upload information about the tabs in **JSON** Format.
But people who are not associated with software development may not be comfortable with **JSON** files.
If the extension can support downloading and uploading of tabs in **text** format (.txt) then the extension can be useful to a broader audience.

About this issue

1. Once a user selects **Download Tabs** button they should get an option to select in which format they want to download their tabs
2. Also when **Upload Tabs** button is clicked text file upload should be supported.

**Comment by F1nn-T** [comment]
Hey, I would like to work on this issue

**Comment by Jitensid** [comment]
yes. Good luck

**Comment by F1nn-T** [comment]
I don't think that 2. Is needed because it is already in this issue:  #5 .

**Comment by Jitensid** [comment]
@F1nn-T Thanks for pointing out the mistake. 
Actually there should be a way to upload txt file to upload information of tabs.

**Comment by Jitensid** [comment]
Closed.
