### ISSUE TITLE
Adding a Copy to ClipBoard Button for TabPort Extension

### ISSUE THREAD

**Issue by Jitensid** [Jitensid/TabPort#7]
Currently the [TabPort chrome extension ](https://chrome.google.com/webstore/detail/tabport/dhkmlpcfghaaiiomhfdndoeghjmimafn)has the ability to download and upload information about the tabs in **JSON** Format.
Sometimes users may wish to just copy the tabs info instead of downloading tabs in such case a copy to clipboard button can be shown at the top right position of the extension. 

About this issue

1. Display a Copy Button at the top right section of the extension.
2. After the button is clicked the information about the tabs is stored in their clipboard.

**Comment by raji2004** [comment]
i would love to be assigned this issue

**Comment by Jitensid** [comment]
Ok The issue is assigned to you! 
On a side note what do you think about this extension ?

**Comment by BijanRegmi** [comment]
Hey, can i try this?
